### ISSUE TITLE
Does not work for local images

### ISSUE THREAD

**Issue by Michkovy** [agoupinets/view-image-context-menu-item#2]
Addon does not display images that are on pages which are on local drives.

For example I got a website copy saved on my HD and one on the internet. They are the same apart from where they are, yet viewing the local version I am unable to display the image via RC>View Image. The context menu entry is there but nothing happens in the browser when clicked. I tried it on the web version and there is works as expected, RC>View Image>Image is the only item in the tab.

**Comment by agoupinets** [comment]
That appears to be due to the add-on not having access to the local file system. For example, `tabs.update({url:...})` which is used for opening an image in the same tab has the following blurb in the url documentation:
```
For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail, with runtime.lastError being set to an error message:
    file: URLs (i.e., files on the filesystem. However, to use a file packaged inside the extension, see below)
```
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update

I'm not sure there is a way to request file system access in firefox?

**Comment by agoupinets** [comment]
After some experimentation, I've put up a new version - 2.3

To address this I've added an alternative code path when the add-on detects that the tab its on and the image its trying to open have the `file://` scheme. I don't appear to be able to create new tabs or windows with a `file://` URL, but I can duplicate tabs and create and follow anchor tags from such pages to `file://` URLs. Using a combination of this I can more or less implement the normal features. One drawback is the parent page gets loaded each time a new tab or window is creates (duplicated) as I cannot get into the appropriate state otherwise.
