### ISSUE TITLE
Support for blob:url and data:image

### ISSUE THREAD

**Issue by look997** [agoupinets/view-image-context-menu-item#20]
For example, Messenger uses blob:url and data:image, and view-image-context-menu simply doesn't support this.

**Comment by agoupinets** [comment]
i'll take a look at this and see whats possible within the constraints of webextentions api

**Comment by agoupinets** [comment]
i think there are three cases that relate to this:
- img element with a `data:image/jpeg;base64,...` url or some variant thereof
- img element with a `blob:www.example.com/some-uuid` blob that isn't a revoked url
- img element with a `blob:www.example.com/some-uuid` that is revoked (purely came across this in example blob generation JS code)

Locally, in a file:// scheme, the first two items just work (the add-on creates an anchor and clicks it), the third item does not (reloads page).

On a server, in a https:// scheme, none of the items work - first two dont do anything, third item loads a blank moz-extension "_generated_background_page.html". The add-on encounters a `Error: Illegal URL` error when calling `browser.tabs.update`. Looks like `data:` and `blob:` urls are considered "privileged" https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update#url

this would be so much easier if this was just done by firefox - the browser already has the images cached and showing, a first class citizen menu item wouldn't need to dance around add-on security limitations or trying to refetch the image. but if they dont want to, i suppose i can try.

**Comment by agoupinets** [comment]
I've listed a new version - 3.4 - with some support (not bothering with revoked urls) for data: and blob: URLs by utilizing the same code i had for file:// URLs. Let me know if i broke anything along the way.

**Comment by look997** [comment]
@agoupinets It works in Messenger with `data:...` and `blob:...`.
When I open it in a new tab (Middle-click), there's a bit of a strange redirect—first, the Messenger tab seems to duplicate, and only then does `data:...`/`blob:...` open. But it works, so it's okay.

**Comment by agoupinets** [comment]
yes, the workaround has to do that - add-ons are not allowed to directly set a url that is priviliged.

When opening a new tab/window, I work around the limitation by duplicating the parent tab (which im allowed to do regardless of its url) and then generating and clicking a hidden anchor tag on the page with the (priviliged) image url immediately after page load. This causes the parent page to be reloaded in those cases.

I needed this specifically when working with the file:// scheme, since i had no other way to create a page that would allow me click file:// urls (firefox refuses to click file:// urls on non-file:// parent pages). There may be a way to work around duplicating the page when dealing with blob: and data: links since the parent page is still an https:// scheme, but i may run into CORS or other security issues when trying to programatically click a link with a url that doesn't properly match up to its parent page (eg if the parent page is about:blank). I will consider investigating this futher in the future.

edit: after a bit of testing - creating an empty page (about:blank) it cannot be modified directly to create a link to click, adding an empty extension page to the add-on (moz-extension: page) blob: links cannot be clicked (even manually) due to security limitations. as of this point, i dont see any way to work around duplicating the parent page since that is the only way i have found that gives me the proper context to click a generated link as a workaround to not being able to set the url of a tab directly. perhaps a different approach by leveraging the existing page w/o duplicating it and using javascript to open a link in a new tab could work but would be its own can of worms to properly support opening foreground tab/background tab/new window.

When opening an privileged url in the same tab, it does not need to duplicate the tab, it directly creates and clicks an anchor on the page.
